@baseurl=http://localhost:3333
@Content=Content-Type: application/json
@eventId=251b5db1-68a8-4c19-b25f-fd5d367a96ad
### Criar evento
POST {{baseurl}}/events
{{Content}}

{
  "title": "Comunidade Aceleragro",
  "details": "A maior comunidade com foco agro",
  "maximumAttendees": null
}


### Registar em um event
POST {{baseurl}}/events/{{eventId}}/attendees
{{Content}}

{
  "name": "Anderson Lopes",
  "email": "anderson_lops@hotmail.com"
}


### Buscar um evento pelo id
GET {{baseurl}}/events/{{eventId}}

### Buscar attendee pelo id
GET {{baseurl}}/attendees/5/badge

###
GET {{baseurl}}/attendees/5/checkin