@baseurl=http://localhost:3333
@Content=Content-Type: application/json
@eventId=538a4e98-97f4-4edb-9955-16ab079c544d
### Criar evento
POST {{baseurl}}/events
{{Content}}

{
  "title": "Teste evento 2",
  "details": null,
  "maximumAttendees": null
}


### Registar em um event
POST {{baseurl}}/events/{{eventId}}/attendees
{{Content}}

{
  "name": "Thais Fernanda Lopes",
  "email": "thaisfernanda@hotmail.com"
}


### Buscar um evento pelo id
GET {{baseurl}}/events/{{eventId}}

### Buscar attendee pelo id
GET {{baseurl}}/attendees/1/badge